name = "manager-money"
main = ".open-next/worker.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "manager-money-db"
database_id = "4ffeee39-cf1b-453e-bb12-bef1ad521003"
migrations_dir = "drizzle"

# KV Namespace for Feature Flags
[[kv_namespaces]]
binding = "FEATURE_FLAGS"
id = "ad6ecec556d74f7484a94f188bf4a8eb"

[vars]
ENVIRONMENT = "production"
FEATURE_AUTH_CREDENTIALS = "true"
FEATURE_MODULE_EV = "true"
FEATURE_MODULE_LIVING_COST = "true"
FEATURE_MODULE_SAVINGS = "true"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
